### ISSUE TITLE
Dumcord -> IRC works but not IRC -> dumcord with exception of one channel

### ISSUE THREAD

**Issue by RoboMWM** [zachbr/Dis4IRC#21]
Idk wat dum is happening but for some reason it'll only 100% bridge messages on one channel, the rest it'll only go from dumcord -> IRC. https://gist.github.com/RoboMWM/b16813f616a5a122f4fd28486ea8eb58

**Comment by RoboMWM** [comment]
Upon more testing, it seems that it doesn't like the IRC channel names. Maybe they're too big? (all IRC channel names match dumcord channel names so nothing there).

**Comment by RoboMWM** [comment]
Got it to work... Sooooooo... it seems casing matters... but only for those two channels. I had to make the IRC channel name all lowercase. But the #MLG one works just fine, while #ROBOMWM (when I tested it like that) did not.

**Comment by zachbr** [comment]
Should be fixed based on my, limited, testing.
Please re-try your original case against master if you want to verify.
Thanks
