### ISSUE TITLE
[Question] How does Dis4IRC handle JDA's auto closing webhook feature?

### ISSUE THREAD

**Issue by doublehelix457** [zachbr/Dis4IRC#29]
Ive noticed that after a while a JDA WebHookClient will automatically close. If i were to run this application for a long period of time using the webhook feature, is it reliable? How is it handled? Some people use guava's cache as a workaround with a removal listener. Just need to know these things before I use the application on a production server.

**Comment by zachbr** [comment]
I am not familiar with any issues relating to our use of the WebHookClient. I'm not even aware offhand of the issue you're referring to but I don't do much with JDA outside of this project.

There are lulls in activity in the guilds I use it on, typically during the very morning hours, but if the webhooks are closing they are coming up quickly enough on my servers that I do not notice. As far as reliability is concerned, I am not aware of ever losing any messages to this phenomenon. Typically that only occurs when Discord's API has some hiccup once a month or so.

**Comment by doublehelix457** [comment]
The reason i ask is because WebHookClient implements an AutoCloseable interface, but if your running bot runs consistently then it sounds like i can close this issue. Is the bot always running for perhaps weeks or months at a time?

**Comment by zachbr** [comment]
I have run it for 2 months without issues in a systemd service. When I make changes to the bot I usually dogfood them myself to try and find issues faster so I never have any super crazy months and months but I'm not aware of any issues. If they were brought to my attention, either because I noticed them or someone else reported it, I would make it a priority to fix them.

**Comment by doublehelix457** [comment]
Much appreciated and thanks for the timely replies!
