### ISSUE TITLE
No reconnect to IRC

### ISSUE THREAD

**Issue by nhnb** [zachbr/Dis4IRC#45]
Dis4IRC was disconnected from irc.freenode.net, but did not try to reconnect. 

The quit message in IRC said 
~~~~
has quit [Quit: Connection to server lost.]
~~~~~

In the console log there was a single message:
~~~~
[07:49:40] [default] [WARN] - IRC connection closed: null reason
~~~~

Unlike issue #31, there is just this one message. No `Will attempt to reconnect` message in a loop. At the time of the issue, the log level was set to info. So no debug information is available until the this happens again. But the "Will attempt to reconnect` is shown as INFO in the other issue report.

**Comment by zachbr** [comment]
GH-44 _should_ have resolved this. Please build master and give it a try.

**Comment by zachbr** [comment]
> 
> 
> As of now, the problem still persists (in the official download and also when building master).
> 
> Once the host loses network for a tiny blip, the bridge won't reconnect.

**Comment by zachbr** [comment]
Lots of debugging later, we have confirmed a race condition in the IRC library that causes this, as well as a fix.
The author is going to look into a proper fix and hopefully a release. Stay tuned.

**Comment by zachbr** [comment]
Plan is to get 1.3.0 out relatively soon hopefully.
If anyone needs this fix sooner you can build master or grab the GH actions build
