### ISSUE TITLE
Add support for Discord sticker forwarding

### ISSUE THREAD

**Issue by Phoenix616** [zachbr/Dis4IRC#57]
Discord added Stickers which are basically animated emojis in big. It would be nice if there was a way to forward them too at least similarly to how custom emojis are forwarded (but ideally including the sticker name too or something, that might be more fo a feature request to prepend sticker and emoji urls with the actual name so one doesn't have to open them)

**Comment by zachbr** [comment]
Here's where we are at the moment. The JSON-based ones will end up being a pain.
![image](https://user-images.githubusercontent.com/1254957/126054729-cbfc7c6a-e9a3-40a3-b623-06ef33d837fc.png)

**Comment by zachbr** [comment]
JSON/Lottie sticker support was added with https://github.com/zachbr/Dis4IRC/commit/1b937effae93653c2faa801db21c03bd73a5d914
