### ISSUE TITLE
Possible CF Filtering/unclear freeze

### ISSUE THREAD

**Issue by disconsented** [zachbr/Dis4IRC#62]
Hello,

I have set up Dis4IRC on a local W10 host for local testing, which was mostly successful.

Upon attempting to move it out of my home network and onto the same VPS that hosts my bouncer (Arch on DO), I was unable to stand it up with the following logs being what's at the end of the logging.

```
Nov 02 00:12:23 disconsented.com java[550405]: [00:12:23] [default] [INFO] - Connecting to Discord API...
Nov 02 00:12:23 disconsented.com java[550405]: [00:12:23] [net.dv8tion.jda.internal.requests.RateLimiter] [TRACE] - Bucket unlimited+GET/gateway:guild_id:channel_id:webhook_id is running 1 requests
Nov 02 00:12:23 disconsented.com java[550405]: [00:12:23] [net.dv8tion.jda.internal.requests.Requester] [TRACE] - Executing request GET https://discord.com/api/v6/gateway
Nov 02 00:12:23 disconsented.com java[550405]: [00:12:23] [net.dv8tion.jda.internal.requests.Requester] [TRACE] - Finished Request GET https://discord.com/api/v6/gateway with code 200
Nov 02 00:12:23 disconsented.com java[550405]: [00:12:23] [net.dv8tion.jda.internal.requests.Requester] [DEBUG] - Received response with following cf-rays: [6a7927eaf86870e0-SJC]
```
Which I believe aligns to https://github.com/zachbr/Dis4IRC/blob/master/src/main/kotlin/io/zachbr/dis4irc/bridge/pier/discord/DiscordPier.kt#L53-L55

I assume it's getting stuck on `awaitReady()` because Cloudflare is being a pain and filtering the address.

The JDA discord suggests updating JDA, since V6 is deprecated, which may be a contributing factor here.

**Comment by zachbr** [comment]
Hello. Sorry for the delay in responding - still very busy.

I have not seen this issue on my own DO instance but battling CF seems like a good assumption. I've bumped JDA to the latest version on `master` now. You may see if that makes a meaningful difference.

**Comment by zachbr** [comment]
Closing for the time being. Let me know if it comes up again I suppose. It seems like this is all just a chase between CF, JDA, and Discord itself.
