### ISSUE TITLE
No prefix regex passes the prefix its supposed to ignore.

### ISSUE THREAD

**Issue by s-cunt-horpe** [zachbr/Dis4IRC#66]
Not sure if it's an issue on my end, tried to look around to find a fix myself but couldn't
So for example, using the default regex you'd have
Discord:
`Foo: Hey!
Bar: .test`
IRC:
`Bridge | <Foo> Hey!`
`Bridge | .test`
but what I'm looking for is to pass the message to IRC without the dot, is there any way I can do that?

**Comment by zachbr** [comment]
This feature is operating as intended. The prefix it's removing is the <Foo> username prefix, not the prefix that trigger the regex itself. It's intended to allow Discord users to execute bot commands in IRC, that are historically just `!info` or `.help`.
