### ISSUE TITLE
Channels with passwords and name formatting errors

### ISSUE THREAD

**Issue by darksageaura** [zachbr/Dis4IRC#69]
I don't know if I am missing something but I was wondering what I would put to have the bot join an irc channel with a password.

**Comment by darksageaura** [comment]
Sorry to bug you along with the top I got the latest build of the bot, and the second bot that I use sees names as like this d?ar?ka?ur?a

**Comment by zachbr** [comment]
> I don't know if I am missing something but I was wondering what I would put to have the bot join an irc channel with a password.

It can but it requires using the `init-commands-list` option to specify the raw command. The main issue is that if it were to be kicked, it currently cannot re-join the channel automatically like it could for non-password protected channels, or channels that authenticate based on NickServ registration. This is usually not an issue - it should still be able to join if it gets disconnected from the server and reconnects later.

```
irc {
    init-commands-list=[
        "JOIN #channelname PASSWORD"
    ]
}
```

> the second bot that I use sees names as like this d?ar?ka?ur?a would it be possible to have the bot display the name as just darkaura for example. This happens when I turn colors off.

This is the anti-ping feature keeping you from pinging yourself in IRC every time you speak in Discord. The bot uses a unicode non-breaking space character (U+00A0) inserted in the nickname to prevent unintended pings. You can disable this functionality by setting `anti-ping` to `false` and restarting the bridge.

**Comment by darksageaura** [comment]
Thank you so much that's was the problem and the fix.
