### ISSUE TITLE
New Discord Names

### ISSUE THREAD

**Issue by darksageaura** [zachbr/Dis4IRC#71]
Hello is there a way to have the bot recognize the username in the discord channel and not the general username used for discord for example if someone's user name for discord is myusername1234, and in a discord channel they use myname. Instead of using myusername123 it recognizes myname. This is just a wishlist thing.

**Comment by zachbr** [comment]
Prior to the Discord username changes, this is how it functioned. With those changes going on currently, I have seen similar uncertain behavior. It's on my list to take a deeper look at this soon. We may see this stabilize as Discord completes its username migration and libraries update.

**Comment by zachbr** [comment]
Can you try this again for me and see if it's working as you expect now? If not, can you clarify this a bit for me?
You can grab the latest build from here until I cut a new release (likely in the next few days): https://nightly.link/zachbr/Dis4IRC/workflows/gradle/master/dis4irc-jar

Currently, it uses the effective name of the person - so if they have not changed their name in your specific guild, it will use their username. If they have set a server nickname, the bot will try and use that instead.

**Comment by darksageaura** [comment]
So what probably had happen is I was on the 1.4.3 snapshot and that what the problem most likely had been. When I updated to the snapshot you sent me it worked just fine....Case of User Error.

**Comment by zachbr** [comment]
No worries. I’m glad it’s working for you.
