### ISSUE TITLE
Parsing URLs

### ISSUE THREAD

**Issue by darksageaura** [zachbr/Dis4IRC#74]
My group and I on discord have found that sometimes in irc the bot parses the url. Is there a way to maybe turn that off or if we have to parse it put the parsing on a different line than the url
![image](https://github.com/zachbr/Dis4IRC/assets/40060780/3dddd0c5-16b6-47f5-a2ce-32b995df087b)

**Comment by zachbr** [comment]
I cannot reproduce this.

Dis4IRC doesn't parse URLs or look them up for additional information. It basically just sends whatever happens in Discord to IRC and vice-versa. Do you have a Discord bot that triggers on certain URLs and replies with an embed? Dis4IRC does attempt to bridge embeds but I can't seem to get Discord to trigger that for a link preview by itself. That feature does need a toggle, but there's not enough here for me to say whether that's related or not.

**Comment by zachbr** [comment]
Hello again. I still can't reproduce this, however if it was a channel embed being bridged, that can now be turned off. If you have additional information, feel free to let me know. Thanks.
