### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by stacyharper** [zachbr/Dis4IRC#82]
Hello,

I'm trying to package Dis4IRC for Alpine Linux, and I'd like to build it from source. But I'm stuck at `fatal: not a git repository (or any of the parent directories): .git`

I'd like to fetch sources from `https://github.com/zachbr/Dis4IRC/archive/refs/tags/v$pkgver.tar.gz`.

The problems seems to comes from the `build.gradle.kts` `getGitHash()`. Can I skip this somehow? If not, it is possible to patch this gradle build to allow this?

Thank for any help ~

**Comment by zachbr** [comment]
It's been on my list for a while to change how this works. This seemed like a good opportunity. This will land in 1.6.4 which I will probably release in the next few days.

Thanks.
